# Generated by Django 3.2.7 on 2021-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StubData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EMSE', models.CharField(max_length=264, null=True)),
                ('ST', models.CharField(max_length=264, null=True)),
                ('MS', models.CharField(max_length=264, null=True)),
                ('HRUP', models.CharField(max_length=264, null=True)),
                ('HR', models.CharField(max_length=264, null=True)),
                ('TH', models.CharField(max_length=264, null=True)),
                ('ET', models.CharField(max_length=264, null=True)),
                ('LYD', models.CharField(max_length=264, null=True)),
                ('LFM', models.CharField(max_length=264, null=True)),
                ('LFSS', models.CharField(max_length=264, null=True)),
                ('LFT', models.CharField(max_length=264, null=True)),
                ('LST', models.CharField(max_length=264, null=True)),
                ('EN', models.CharField(max_length=264, null=True)),
                ('EA', models.CharField(max_length=264, null=True)),
                ('CN', models.CharField(max_length=264, null=True)),
                ('CA', models.CharField(max_length=264, null=True)),
                ('SSN', models.CharField(max_length=264, null=True)),
                ('RP', models.CharField(max_length=264, null=True)),
                ('PD', models.CharField(max_length=264, null=True)),
                ('CK', models.CharField(max_length=264, null=True)),
                ('FMT', models.CharField(max_length=264, null=True)),
                ('FMY', models.CharField(max_length=264, null=True)),
                ('FSST', models.CharField(max_length=264, null=True)),
                ('FSSY', models.CharField(max_length=264, null=True)),
                ('FtT', models.CharField(max_length=264, null=True)),
                ('FtY', models.CharField(max_length=264, null=True)),
                ('StT', models.CharField(max_length=264, null=True)),
                ('StY', models.CharField(max_length=264, null=True)),
                ('YTDG', models.CharField(max_length=264, null=True)),
                ('YTDD', models.CharField(max_length=264, null=True)),
                ('YTDN', models.CharField(max_length=264, null=True)),
                ('TTL', models.CharField(max_length=264, null=True)),
                ('DED', models.CharField(max_length=264, null=True)),
                ('NP', models.CharField(max_length=264, null=True)),
            ],
        ),
    ]
