# Generated by Django 3.2.7 on 2021-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubmaker_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stubdata',
            name='CPY',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
